# Define as versões dos serviços necessários
[build]
  command = "yarn build"
  publish = ".next/"  # Atualize para a pasta correta

# Define as variáveis de ambiente necessárias
[build.environment]
  NODE_VERSION = "19"
  NETLIFY_ENV = "production"

